INSERT INTO PersonaPool (id, name, avatar, bio) VALUES
  ('countess-snuffles', 'Countess Snuffles', '🐱', 'Aristocratic feline with a taste for drama'),
  ('dr-spatula', 'Dr. Spatula', '🍔', 'Culinary genius, terrible bedside manner'),
  ('baron-von-bon-bon', 'Baron Von Bon Bon', '🍬', 'Sweet on the outside, ruthless within'),
  ('captain-quack', 'Captain Quack', '🦆', 'Navigates every situation with aplomb'),
  ('lady-fingers', 'Lady Fingers', '💅', 'Elegance is her weapon of choice'),
  ('sir-loin', 'Sir Loin', '🥩', 'A cut above the rest'),
  ('madame-mist', 'Madame Mist', '🌫️', 'Nobody sees her coming'),
  ('professor-puns', 'Professor Puns', '🤡', 'Armed with wordplay and dad jokes'),
  ('duchess-dynamite', 'Duchess Dynamite', '💥', 'Explosive personality, short fuse'),
  ('chef-chaos', 'Chef Chaos', '🔥', 'Too many cooks? Never enough'),
  ('the-oracle', 'The Oracle', '🔮', 'Sees all, tells nothing'),
  ('pixel-pete', 'Pixel Pete', '👾', '8-bit brain in a 4K world'),
  ('shadow-fox', 'Shadow Fox', '🦊', 'Trust no one, suspect everyone'),
  ('queen-bee', 'Queen Bee', '🐝', 'Runs the hive with an iron stinger'),
  ('mad-hatter', 'Mad Hatter', '🎩', 'Sanity is overrated'),
  ('iron-maiden', 'Iron Maiden', '⚔️', 'Forged in fire, tempered by betrayal'),
  ('velvet-viper', 'Velvet Viper', '🐍', 'Smooth talker with a venomous bite'),
  ('disco-inferno', 'Disco Inferno', '🪩', 'Burns bright on every dance floor'),
  ('phantom-ink', 'Phantom Ink', '🖊️', 'Writes the rules, then rewrites them'),
  ('neon-ninja', 'Neon Ninja', '🥷', 'Silent but impossible to miss'),
  ('cosmic-carl', 'Cosmic Carl', '🚀', 'Lost in space, found in drama'),
  ('glitch-witch', 'Glitch Witch', '🧙‍♀️', 'Reality bends around her'),
  ('turbo-tortoise', 'Turbo Tortoise', '🐢', 'Slow to act, first to finish'),
  ('static-storm', 'Static Storm', '⚡', 'Charges up when the pressure is on');
